name: Format

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: julia-actions/julia-format@master
      with:
        args: --verbose --indent 4 --margin 80  --always_for_in --whitespace_typedefs --whitespace_ops_in_indices .
